export const DEFAULT_OVERLAYS_SHOW_TIMEOUT = 2000;
export const DEFAULT_PERSISTANTLY_SHOW_OVERLAYS = false;
export const DEFAULT_SKIP_ALL_SYSTEM_EVENTS = false;
export const DEFAULT_HIDE_OVERLAYS_ON_MOUSE_LEAVE = true;
export const DEFAULT_SHOW_OVERLAYS_ON_MOUSE_MOVE = true;
export const DEFAULT_UNMOUNT_CONTENT_WHEN_HIDDEN = false;